### ISSUE TITLE
MSRV?

### ISSUE THREAD

**Issue by palfrey** [slint-ui/document-features#6]
Doesn't seem to document the Minimum Supported Rust Version for this crate. Guessing 1.54.0 from the CI?

**Comment by ogoffart** [comment]
This is explained there: https://docs.rs/document-features/latest/document_features/#compatibility
So that's right, the MSRV is 1.54,  but I recommend making the use of that crate optional and only enabled when building the docs. That way you can still use it in crates that supports very old rust versions.
